### ISSUE TITLE
Syntax issue

### ISSUE THREAD

**Issue by 8cris2** [franzheidl/bemify#3]
I receive this error when the compiler builds code in sass --watch project.

Syntax error: Invalid CSS after "...ator}#{$prefix}": expected "{", was "-#{$state} {"

 "-#{$state" may only be used at the beginning of a compound selector. on line 69 of bower_components/bemify/sass/_bemify.scss from line 1 of sass/styles.scss 
64:}

**Comment by franzheidl** [comment]
Hi, please post 

a) the platform/version of Sass you're using

b) the complete scss source of the selector that causes the error. If nested (which I presume), up to the root level.

Otherwise it's just guesswork for me, thanks.

**Comment by 8cris2** [comment]
Hi there. 

I figured the issue I was experiencing. It was my version of sass. It was outdated. I tried a few different sass bem libraries from sache.in and I encountered the same syntax issue as the above mentioned in my previous post. It is all working correctly now as i've updated my sass version. 

Cheers
