### ISSUE TITLE
Correction: .io/bemify doc has wrong is-happy example

### ISSUE THREAD

**Issue by goesbysteve** [franzheidl/bemify#4]
Not an issue but thought I'd let you know that the __child--bad/.ishappy example of the .io/bemify is wrong. It has .my-element__child--bad.is-happy rather than .my-element__child.is-happy. On github readme it's correct though.

Hope this helps.

**Comment by franzheidl** [comment]
Good catch, many thanks! 
Just fixed this on the site to be correct and identical with RM.

**Comment by goesbysteve** [comment]
No problem! Thanks for making the project available.
